language: android
jdk: oraclejdk8
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_63bf676bf253_key -iv $encrypted_63bf676bf253_iv
  -in android.keystore.enc -out android.keystore -d
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.1.1
  - android-27
script: ./gradlew assembleRelease
deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file: "app/build/outputs/apk/app-release.apk"
  skip_cleanup: true
  on:
    tags: true
